spring:
  application:
    name: flashcard

  datasource:
    url: jdbc:mysql://localhost:3306/flash-cards?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true
    open-in-view: false

server:
  port: 8080
  error:
    include-stacktrace: never